server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/metadata_db # use of local postgresql server
    username: metadata_db_admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create # create the db on the first run, and updates it in subsequent
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
        use_sql_comments: true

